site_name: "ynab-transaction-adjuster"

theme:
  name: readthedocs
  analytics:
    gtag: G-CQYD14VWNV

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [ynabtransactionadjuster]
        enable_inventory: true
        options:
          docstring_style: sphinx
          show_root_heading: true
          show_root_full_path: true
          show_root_toc_entry: true
          show_source: false
#          show_signature_annotations: true
          signature_crossrefs: true
          parameter_headings: false
          heading_level: 3
          line_length: 80

nav:
  - 'index.md'
  - 'basic_usage.md'
  - 'detailed_usage.md'
  - 'reference.md'

markdown_extensions:
- footnotes
- admonition
